filebeat.inputs:
  - type: filestream
    id: nginx-access
    paths: [/var/log/nginx/access.log]
    fields_under_root: true
    fields:
      input_id: nginx-access
      service: nginx
      log_type: access

  - type: filestream
    id: nginx-error
    paths: [/var/log/nginx/error.log]
    fields_under_root: true
    fields:
      input_id: nginx-error
      service: nginx
      log_type: error


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "nginx-%{[log_type]}-%{+yyyy.MM.dd}"



setup.ilm.enabled: false
setup.template.enabled: false

logging.level: info